#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.refractored.controls.Resource", IsApplication=true)]

namespace com.refractored.controls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int typeface = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000a
			public const int roboto_black = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int roboto_black_italic = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int roboto_bold = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int roboto_bold_italic = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int roboto_condensed = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int roboto_condensed_bold = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int roboto_condensed_bold_italic = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int roboto_condensed_italic = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int roboto_italic = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int roboto_light = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int roboto_light_italic = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int roboto_medium = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int roboto_medium_italic = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int roboto_regular = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int roboto_thin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int roboto_thin_italic = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RobotoTextView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int RobotoTextView_typeface = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
